name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '6.1.0'
    - name: Build
      run: swift build -v
